const d = window.PORTFOLIO_DATA;
const $ = (id) => document.getElementById(id);
$("name").textContent = d.name;
$("role").textContent = d.role;
$("intro").textContent = d.intro;
$("resumeLink").href = d.resume;
$("linkedinLink").href = d.linkedin;
$("linkedinLink2").href = d.linkedin;
$("emailLink").href = `mailto:${d.email}`;
$("location").textContent = d.location;
$("footerName").textContent = d.name;
$("metricGrid").innerHTML = d.metrics.map(m => `<article class="metric-card"><strong>${m.value}</strong><span>${m.label}</span><small>${m.detail || ""}</small></article>`).join("");
$("fsTitle").textContent = d.formulaStudent.title;
$("fsSubtitle").textContent = d.formulaStudent.subtitle;
$("fsOverview").textContent = d.formulaStudent.overview;
$("fsHero").src = d.formulaStudent.heroImage;
$("fsResponsibilities").innerHTML = d.formulaStudent.responsibilities.map(x => `<li>${x}</li>`).join("");
$("conceptNote").textContent = d.formulaStudent.conceptClassNote;
$("developmentGrid").innerHTML = d.formulaStudent.development.map(p => `<a class="dev-card" href="${p.href}"><img src="${p.image}" alt="${p.title}" loading="lazy" /><div class="card-copy"><h3>${p.title}</h3><p>${p.text}</p><span class="card-link">View full case study →</span></div></a>`).join("");
$("fsResults").innerHTML = d.formulaStudent.results.map(x => `<li>${x}</li>`).join("");
$("researchTitle").innerHTML = `<a href="${d.research.href}">${d.research.title}</a>`;
$("researchJournal").textContent = d.research.journal;
$("researchSummary").textContent = d.research.summary;
$("doiLink").href = d.research.doi;
$("researchMetrics").innerHTML = d.research.metrics.map(m => `<article class="metric-card"><strong>${m.value}</strong><span>${m.label}</span></article>`).join("");
$("projectGrid").innerHTML = d.universityProjects.map(p => `<a class="project-card" href="${p.href}"><img src="${p.image}" alt="${p.title}" loading="lazy" /><div class="card-copy"><h3>${p.title}</h3><p>${p.text}</p><span class="card-link">View full case study →</span></div></a>`).join("");
$("skillsGrid").innerHTML = Object.entries(d.skills).map(([group, items]) => `<article class="skill-card"><h3>${group}</h3><div class="tags">${items.map(i => `<span class="tag">${i}</span>`).join("")}</div></article>`).join("");